from tkinter import *
from tkinter.ttk import Checkbutton, Radiobutton

window = Tk()
window.title("Лето приближается!")
window.geometry('500x500')
label = Label(window, text="Скоро лето!!!", font=("Arial", 16))
label.pack(pady=10)
chk1_state = BooleanVar()
chk2_state = BooleanVar()
chk3_state = BooleanVar()
chk1 = Checkbutton(window, text="Флажок 1", variable=chk1_state)
chk2 = Checkbutton(window, text="Флажок 2", variable=chk2_state)
chk3 = Checkbutton(window, text="Флажок 3", variable=chk3_state)
chk1.pack(anchor='w', padx=20)
chk2.pack(anchor='w', padx=20)
chk3.pack(anchor='w', padx=20)
selected = IntVar()
rad1 = Radiobutton(window, text="Радио 1", value=1, variable=selected)
rad2 = Radiobutton(window, text="Радио 2", value=2, variable=selected)
rad3 = Radiobutton(window, text="Радио 3", value=3, variable=selected)
rad1.pack(anchor='w', padx=20, pady=(10, 0))
rad2.pack(anchor='w', padx=20)
rad3.pack(anchor='w', padx=20)
window.mainloop()
